# Generated by Django 4.1.5 on 2023-01-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
